"""empty message

Revision ID: 594200a81efa
Revises: 7ea125005547
Create Date: 2024-05-15 23:55:23.800903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594200a81efa'
down_revision = '7ea125005547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('community')
    # ### end Alembic commands ###
