"""empty message

Revision ID: 7ff05c5abbba
Revises: 9210a823e9bc
Create Date: 2024-05-10 05:13:19.957002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff05c5abbba'
down_revision = '9210a823e9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth', sa.Date(), nullable=True))
        batch_op.drop_column('birthday')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthday', sa.DATE(), nullable=True))
        batch_op.drop_column('birth')

    # ### end Alembic commands ###
