"""empty message

Revision ID: 8fc71b458b75
Revises: 358127aedbd8
Create Date: 2024-05-19 21:00:46.602426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fc71b458b75'
down_revision = '358127aedbd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pma_activity_month', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_done', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pma_activity_month', schema=None) as batch_op:
        batch_op.drop_column('is_done')

    # ### end Alembic commands ###
