"""empty message

Revision ID: 9c701b33cb3e
Revises: 8fc71b458b75
Create Date: 2024-05-19 21:13:42.179065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c701b33cb3e'
down_revision = '8fc71b458b75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pma_activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('responsible_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_responsible_id_app_users', 'app_users', ['responsible_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pma_activity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('responsible_id')

    # ### end Alembic commands ###
