"""pongo db.Model en common Models

Revision ID: dd6027b7f773
Revises: 9c701b33cb3e
Create Date: 2024-05-20 05:47:23.941536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd6027b7f773'
down_revision = '9c701b33cb3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['responsible_id'], ['app_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('pma_activity')
    with op.batch_alter_table('pma_activity_month', schema=None) as batch_op:
        batch_op.drop_index('ix_pma_activity_month_month_id')
        batch_op.drop_index('ix_pma_activity_month_pma_activity_id')

    op.drop_table('pma_activity_month')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pma_activity_month',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('month_id', sa.INTEGER(), nullable=True),
    sa.Column('pma_activity_id', sa.INTEGER(), nullable=True),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('is_done', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['month_id'], ['month.id'], ),
    sa.ForeignKeyConstraint(['pma_activity_id'], ['pma_activity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pma_activity_month', schema=None) as batch_op:
        batch_op.create_index('ix_pma_activity_month_pma_activity_id', ['pma_activity_id'], unique=False)
        batch_op.create_index('ix_pma_activity_month_month_id', ['month_id'], unique=False)

    op.create_table('pma_activity',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('responsible_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['responsible_id'], ['app_users.id'], name='fk_responsible_id_app_users'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('activity')
    # ### end Alembic commands ###
